# Generated by Django 5.0.1 on 2025-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_de_nascimento',
            field=models.DateField(null=True),
        ),
    ]
