# Generated by Django 5.0.1 on 2025-05-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_user_cnpj_user_contato_user_descricao_pessoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
