# Generated by Django 5.1.6 on 2025-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('PAG', 'Pago')], max_length=3)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
