# Generated by Django 5.0.1 on 2025-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='blog')),
                ('tags', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['id'],
            },
        ),
    ]
