# Generated by Django 5.0.1 on 2025-04-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('comunidade', '0002_alter_comunidade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='comunidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogPosts', to='comunidade.comunidade'),
            preserve_default=False,
        ),
    ]
