# Generated by Django 5.0.1 on 2025-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts_comunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='upload',
            field=models.FileField(upload_to='blog'),
        ),
    ]
