# Generated by Django 5.0.1 on 2025-05-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogposts_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
