# Generated by Django 5.0.1 on 2025-05-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogposts_likes'),
        ('comunidade', '0002_alter_comunidade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogPosts', to='comunidade.comunidade'),
        ),
    ]
