# Generated by Django 5.0.1 on 2025-05-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0002_alter_comunidade_options'),
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='comunidade.comunidade'),
        ),
    ]
