# Generated by Django 5.0.1 on 2025-03-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0001_initial'),
        ('postagem', '0002_alter_postagem_options_postagem_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='comunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='comunidade.comunidade'),
        ),
    ]
