# Generated by Django 5.0.1 on 2025-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0002_alter_postagem_comunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='posts'),
        ),
    ]
