# Generated by Django 5.0.1 on 2025-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0003_alter_postagem_comunidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['id'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
    ]
