# Generated by Django 5.0.1 on 2025-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0003_postagem_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
