# Generated by Django 5.1.6 on 2025-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ABE', 'Aberto'), ('AND', 'Em Andamento'), ('CON', 'Concluído')], max_length=3)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
