# Generated by Django 5.0.1 on 2025-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_alter_processo_options_processo_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['id'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
    ]
