# Generated by Django 5.1.6 on 2025-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('receita_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesas_totais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
