# Generated by Django 5.0.1 on 2025-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidade',
            options={'ordering': ['id'], 'verbose_name': 'Comunidade', 'verbose_name_plural': 'Comunidades'},
        ),
    ]
