# Generated by Django 5.1.6 on 2025-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('AGE', 'Agendada'), ('REA', 'Realizada'), ('CAN', 'Cancelada')], max_length=3)),
            ],
        ),
    ]
