# Generated by Django 5.1.6 on 2025-03-27 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nome_advogado', models.CharField(max_length=100)),
                ('oab_advogado', models.CharField(max_length=20)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('data_hora', models.DateTimeField()),
                ('duracao', models.PositiveIntegerField(default=60, help_text='Duração em minutos', validators=[django.core.validators.MinValueValidator(30)])),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data_hora'],
            },
        ),
    ]
