# Generated by Django 5.1.6 on 2025-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_consulta_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['criacao'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='advogado',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='valor',
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_cliente',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='numero_processo',
            field=models.CharField(max_length=50),
        ),
    ]
