# Generated by Django 5.0.1 on 2025-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_consulta_options_remove_consulta_advogado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='assunto',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
