# Generated by Django 5.1.6 on 2025-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advogado',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-03 12:00:00'),
            preserve_default=False,
        ),
    ]
